#!/bin/bash

# patched version of downloaded from
#   https://wkhtmltopdf.org/downloads.html
#
# Usage wrapper.sh file-in title

FILE_IN=$1
TITLE=$2

if [ "$3" == '' ]
then
	MARGIN=10mm
else
	MARGIN=$3
fi

cd `dirname $0`
./transform.mjs $FILE_IN $TITLE

FILE_IN=/tmp/md2.html # generated by convert.mjs
TITLE=${TITLE,,} # to lower case
TITLE="${TITLE// /-}"  # replace spaces with -
PDF_PATH=/tmp/$TITLE.pdf
../html-to-pdf.mjs $FILE_IN $PDF_PATH
rm $FILE_IN
